<?php

/**
 * @file captcha_keypad.module
 * Captcha keypad module.
 */

/**
 * Implements hook_help().
 */
function captcha_keypad_help($path, $arg) {
  switch ($path) {
    case 'admin/config/captcha_keypad':
      return '<p>' . t('todo.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function captcha_keypad_menu() {
  $items = array();

  $items['admin/config/system/captcha_keypad'] = array(
    'title' => 'Captcha Keypad',
    'description' => 'Configure Captcha Keypad.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('captcha_keypad_settings_form'),
    'access arguments' => array('administer captcha keypad'),
    'file' => 'captcha_keypad.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function captcha_keypad_permission() {
  $permissions = array();

  $permissions['administer captcha keypad'] = array(
    'title' => t('Administer Capcha keypad'),
  );
  return $permissions;
}

/**
 * Implements hook_form_alter().
 */
function captcha_keypad_form_alter(&$form, &$form_state, $form_id) {
  var_dump($form_id);

  $forms = array('user_login', 'article_node_form','comment_node_article_form'); //@todo use variable_get

  if (!in_array($form_id, $forms)) {
    return;
  }

  $code_size = variable_get('captcha_keypad_code_size', 4);
  $code = '1234';

  $form['captcha_keypad'] = array(
    '#title' => t('Security'),
    '#type' => 'fieldset',
  );

  $form['captcha_keypad']['captcha_keypad_input'] = array(
    '#title' => t('Enter code'),
    '#type' => 'textfield',
    '#size' => $code_size,
  );

  $form['captcha_keypad']['captcha_keypad_hidden'] = array(
    '#type' => 'hidden',
    '#value' => $code,
  );

  $keypad = '';
  for ($n=1; $n<=9; $n++) {
    $keypad .= '<span>' . $n . '</span>';
  }
  $form['captcha_keypad']['keypad'] = array(
    '#prefix' => '<span class="captcha-keypad"><span class="inner">',
    '#markup' => $keypad,
    '#suffix' => '</span></span>',
  );

  $form['captcha_keypad']['code'] = array(
    '#prefix' => '<span>',
    '#markup' => t('Using the keypad, enter the following code: <strong>:code</strong>', array(':code' => $code)),
    '#suffix' => '</span>',
  );

  $form['#validate'][] = 'captcha_keypad_form_validate';

  _captcha_keypad_add_js_css();
}

/**
 * Callback function for form submit.
 */
function captcha_keypad_form_validate(&$form, &$form_state) {
  if ($form_state['values']['captcha_keypad_input'] != $form_state['values']['captcha_keypad_hidden']) {
    _captcha_keypad_add_js_css();
    form_set_error('captcha_keypad_input', t('Invalid security code.'));
  }
}

/**
 * Helper to add css and javascript.
 */
function _captcha_keypad_add_js_css() {
  drupal_add_js(drupal_get_path('module', 'captcha_keypad') . '/captcha_keypad.js');
  drupal_add_css(drupal_get_path('module', 'captcha_keypad') . '/captcha_keypad.css');
}
