# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    machine: true
    steps:
      - run: |
          docker run marcellovani/drupalci:8-fpm-alpine /bin/sh -c "sh runtests.sh 8 ${CIRCLE_PROJECT_REPONAME} 1.x-dev"
