# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker run --name drupalci --rm marcellovani/drupalci:8-fpm-alpine /bin/sh -c "sh runtests.sh 8 captcha_keypad 1.x-dev"